---
title: "Pred1 mediation graph"
author: "Alexandra Alexiev"
date: "2025-01-15"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
# knit options for whole doc. I will add in specific chunks when I don't want this to be the case
knitr::opts_chunk$set(echo = TRUE, # show code
                      eval = TRUE, # run chunks when knitting
                      include = TRUE, # include chunk input in final doc
                      warning = FALSE, # do not show warnings in final doc
                      message = FALSE, # do not show messages from code in final doc
                      collapse = TRUE, # when possible, do put multiple outputs in one block
                      dpi = 300, # fig resolution
                      fig.dim = c(9, 5), # the default figure dimensions
                      out.width = "98%", # the default figure output width
                      out.height = "98%", # the default figure output height 
                      cache = TRUE) # dont rerun chunks that haven't been changed

```

## libraries and directories

```{r libraries}
library(tibble)
library(dplyr)
library(vegan)
library(ggplot2)
library(igraph)
library(ggraph)
library(tidygraph)
set.seed(3)

```

```{r set working dir, eval=F}
setwd("/Users/alexieva/Documents/Projects/Analysis/broccoli project/02_pubAnalysis/Prediction1_mediation/")

load("/Users/alexieva/Documents/Projects/Analysis/broccoli project/02_pubAnalysis/Prediction1_mediation/Pred1_medgraph.RData")

```

## Input data

```{r read in data}
# read in mediation results
signif_meds <- read.table(file = "../input_data/signif_meds_pred1.txt",
                          sep = "\t", header = T) %>%
  dplyr::select(-Mediation)

# read in mediation code input file from prediction 1
med_input <- read.table(file = "../outputs/med_input_pred1.txt")


```


## run lm's and add results to input
Two lm's to run here:
lm(log(asv abundance + 1) ~ diet)
lm(log(SFN + 1) ~ log(asv abundance + 1) + diet)
```{r lm's and results added to input file}
# lm's for SFN to ASV
signif_meds$cor1 <- apply(signif_meds, 1, function(x) lm(log(med_input[[x[1]]] + 1) ~ log(med_input[[x[2]]] + 1) + med_input[[x[3]]])$coefficients[2])

# for (i in 1:nrow(signif_meds)) {
#   y <- log(med_input[[signif_meds[i,1]]] + 1)
#   x <- log(med_input[[signif_meds[i,2]]] + 1)
#   mod <- lm(y ~ x)
#   
# }

# lm's for ASV to diet
signif_meds$cor2 <- apply(signif_meds, 1, function(x) lm(log(med_input[[x[2]]] + 1) ~ med_input[[x[3]]])$coefficients[2])


```

Make a file with all the labels and positions for the graph
```{r make label/position file}
# make a label to position file
labpos_SFN <- data.frame(SFN = unique(signif_meds$SFN),
                     sfn_position = seq(from = 1, to = length(unique(signif_meds$SFN)), by = 1))
# labpos_taxa <- data.frame(Genus = unique(signif_meds$Genus),
#                      taxa_position = seq(from = 1, to = length(unique(signif_meds$Genus)), by = 1))
labpos_diet <-data.frame(Diet = unique(signif_meds$Diet),
                     diet_position = seq(from = 1, to = length(unique(signif_meds$Diet)), by = 1))

# add positions to signif meds to connect to graphing data frame down the line
signif_meds_pos <- signif_meds %>%
  inner_join(labpos_SFN, by = "SFN") %>%
  # inner_join(labpos_taxa, by = "Genus") %>%
  inner_join(labpos_diet, by = "Diet")
signif_meds_pos <- signif_meds_pos[order(signif_meds_pos$Genus),] %>%
  mutate(taxa_position_names = c(1, 4, 4, 4, 4, 4, 7.5, 7.5, 11, 11, 11, 11, 11, 14,
                           15.5, 15.5, 17),
         taxa_position = seq(1, 17, by = 1))


```


## make graph

```{r make tile and segment graph}
library("ggnewscale")

# plot
mediation_results_plot <- ggplot(data = signif_meds_pos) +
  geom_segment(aes(x = 1+0.35, xend = 3-0.4, 
                   y = diet_position+5, yend = taxa_position,
                   color = cor1)) +
  scale_color_gradient2(name = "Estimated Coefficient\nTaxa to SFN", 
                        low = "red", mid = "white", high = "blue",
                        midpoint = 0) +
  new_scale_color() +
  geom_segment(aes(x = 3+0.4, xend = 5-0.35, 
                   y = taxa_position, yend = sfn_position+5, 
                   color = cor2)) +
  scale_color_gradient2(name = "Estimated Coefficient\nDiet to Taxa", 
                        low = "red", mid = "white", high = "blue",
                        midpoint = 0) +
  geom_tile(data = labpos_diet, aes(x = 1, y = diet_position+5), height = 0.85, width = 0.7, fill="white", color="black") +
  geom_text(data = labpos_diet, aes(x = 1, y = diet_position+5, label = Diet),
            size = 4) +
  geom_tile(aes(x = 3, y = taxa_position), 
            height = 0.85, width = 0.9, fill="white", color="black") +
  geom_text(aes(x = 3, y = taxa_position, label = Genus),
            size = 4) +
  geom_tile(data = labpos_SFN, aes(x = 5, y = sfn_position+5), height = 0.85, width = 0.7, fill="white", color="black") +
  geom_text(data = labpos_SFN, aes(x = 5, y = sfn_position+5, label = SFN),
            size = 4) +
  theme_void() +
  theme(legend.position="bottom") +
  scale_x_continuous(
    breaks = c(1, 3, 5),
    labels = c("Diet components", "Taxa", "SFN metabolites"),
    position = "top") +
  theme(axis.text.x=element_text(size = 20, face = "bold"),
        plot.background = element_rect(fill = "lightgrey")) +
  labs(fill="")

# ggsave("../outputs/signif_meds_network.png",
#        mediation_results_plot,
#        dpi = 300,
#        height = 7.5,
#        width = 14)

```


## save image chunk 
```{r save env, eval = F}
save.image("/Users/alexieva/Documents/Projects/Analysis/broccoli project/02_pubAnalysis/Prediction1_mediation/Pred1_medgraph.RData")

```